<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NUnit.Extensibility</RootNamespace>
    <TargetFrameworks>net462;net8.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnitLite" />
    <PackageReference Include="NUnit.Analyzers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\nunit.extensibility\nunit.extensibility.csproj" />
  </ItemGroup>

</Project>
