<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NUnit</RootNamespace>
    <TargetFrameworks>net462;net8.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\TestData\mock-assembly\mock-assembly.csproj" />
    <ProjectReference Include="..\nunit.common\nunit.common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnitLite" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="XmlUnit.NUnit4.Constraints" />
  </ItemGroup>

</Project>
